version: "3.8"
services:
  web:
    image: "gitlab/gitlab-ce:latest"
    container_name: gitlab
    restart: always
    ports:
      - "8080:80"
      - "1001:22"
    volumes:
      - "gitlab_config:/etc/gitlab"
      - "gitlab_logs:/var/log/gitlab"
      - "gitlab_data:/var/opt/gitlab"
    shm_size: "4gb"
  runner:
    image: "gitlab/gitlab-runner:latest"
    container_name: gitlab-runner
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/gitlab-runner/config:/etc/gitlab-runner"

volumes:
  gitlab_config: {}
  gitlab_logs: {}
  gitlab_data: {}

networks:
  gitlab:
